version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing Yarn...
      - npm install --global yarn
      - yarn --version
      - echo Installing Dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    on-failure: ABORT 
    commands:
      - echo 'syncing changes'
      - aws s3 sync build/ s3://bengittins.com/ --delete
      - echo Build completed on `date`
