version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing Yarn...
      - npm install --global yarn
      - yarn --version
      - echo Installing Dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/static/**
    - build/asset-manifest.json
    - build/favicon.ico
    - build/favicon.png
    - build/index.html
    - build/manifest.json
    - build/precache-manifest.*
    - build/robots.txt
    - build/service-workers.js
  name: bengittins-com-$(date +%Y-%m-%d)
